/**
 * HX Codebase Map Generator
 *
 * Generates and manages CODEBASE.md — a structured map of the project's
 * file/directory layout that the agent can inject as context.
 *
 * The map is written to .hx/CODEBASE.md and updated incrementally.
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, basename, extname } from "node:path";
import { hxRoot } from "./paths.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CodebaseMapOptions {
  /** Glob-style patterns to exclude. Merged with DEFAULT_EXCLUDE_PATTERNS. */
  excludePatterns?: string[];
  /** Maximum number of files to include. Default: 500. */
  maxFiles?: number;
  /**
   * Collapse directories with N or fewer files into a single entry.
   * Set to 0 to disable collapsing. Default: 3.
   */
  collapseThreshold?: number;
  /** Root directory to scan. Defaults to process.cwd(). */
  rootDir?: string;
}

export interface CodebaseMapEntry {
  /** Relative path from project root */
  path: string;
  /** true = directory, false = file */
  isDir: boolean;
  /** File extension (e.g. ".ts") or empty string for directories */
  ext: string;
  /** Depth from project root (0 = root-level entries) */
  depth: number;
}

export interface CodebaseMapStats {
  totalFiles: number;
  totalDirs: number;
  filesByExtension: Record<string, number>;
  topLevelEntries: number;
  generatedAt: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default patterns to exclude from the codebase map. */
export const DEFAULT_EXCLUDE_PATTERNS: string[] = [
  ".hx/",
  ".git/",
  "node_modules/",
  "dist/",
  "dist-test/",
  ".next/",
  ".nuxt/",
  "build/",
  "coverage/",
  "__pycache__/",
  ".pytest_cache/",
  ".venv/",
  "venv/",
  ".DS_Store",
  "*.lock",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
];

const CODEBASE_MAP_HEADER = "# Codebase Map\n\nGenerated by HX. Shows the file/directory layout of this project.\n\n";

// ---------------------------------------------------------------------------
// Pattern matching
// ---------------------------------------------------------------------------

/**
 * Check whether a path should be excluded based on the given patterns.
 * Patterns ending in "/" match directories; others match files or dirs by name.
 */
function shouldExclude(entryPath: string, patterns: string[]): boolean {
  const normalized = entryPath.replace(/\\/g, "/");
  const name = basename(normalized);

  for (const pattern of patterns) {
    // Directory pattern: "node_modules/"
    if (pattern.endsWith("/")) {
      const dir = pattern.slice(0, -1);
      if (name === dir || normalized.includes(`/${dir}/`) || normalized.startsWith(`${dir}/`)) {
        return true;
      }
      continue;
    }
    // Wildcard pattern: "*.lock"
    if (pattern.startsWith("*")) {
      const ext = pattern.slice(1); // e.g. ".lock"
      if (name.endsWith(ext)) return true;
      continue;
    }
    // Exact name match
    if (name === pattern || normalized === pattern) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Scanner
// ---------------------------------------------------------------------------

interface ScanResult {
  entries: CodebaseMapEntry[];
  truncated: boolean;
}

function scanDir(
  dir: string,
  rootDir: string,
  patterns: string[],
  maxFiles: number,
  collapseThreshold: number,
  currentCount: { n: number },
  depth: number,
): CodebaseMapEntry[] {
  if (currentCount.n >= maxFiles) return [];

  let entries: CodebaseMapEntry[] = [];

  let dirEntries: string[];
  try {
    dirEntries = readdirSync(dir).sort();
  } catch {
    return [];
  }

  for (const name of dirEntries) {
    const fullPath = join(dir, name);
    const relPath = relative(rootDir, fullPath).replace(/\\/g, "/");

    if (shouldExclude(relPath, patterns) || shouldExclude(name, patterns)) continue;

    let st;
    try { st = statSync(fullPath); } catch { continue; }

    if (st.isDirectory()) {
      // Peek at child count for collapsing
      let childCount = 0;
      try { childCount = readdirSync(fullPath).length; } catch { /* ignore */ }

      entries.push({ path: relPath, isDir: true, ext: "", depth });

      if (collapseThreshold > 0 && childCount <= collapseThreshold) {
        // Include children inline without recursing further
        try {
          for (const child of readdirSync(fullPath).sort()) {
            if (currentCount.n >= maxFiles) break;
            const childRel = `${relPath}/${child}`;
            if (shouldExclude(childRel, patterns) || shouldExclude(child, patterns)) continue;
            const childExt = extname(child);
            entries.push({ path: childRel, isDir: false, ext: childExt, depth: depth + 1 });
            currentCount.n++;
          }
        } catch { /* ignore */ }
      } else {
        const children = scanDir(fullPath, rootDir, patterns, maxFiles, collapseThreshold, currentCount, depth + 1);
        entries = entries.concat(children);
      }
    } else {
      entries.push({ path: relPath, isDir: false, ext: extname(name), depth });
      currentCount.n++;
      if (currentCount.n >= maxFiles) break;
    }
  }

  return entries;
}

// ---------------------------------------------------------------------------
// parseCodebaseMap
// ---------------------------------------------------------------------------

/**
 * Parse an existing CODEBASE.md into CodebaseMapEntry objects.
 * Returns empty array if the file is blank or unparseable.
 */
export function parseCodebaseMap(raw: string): CodebaseMapEntry[] {
  const entries: CodebaseMapEntry[] = [];
  for (const line of raw.split("\n")) {
    // Lines look like: "  - `src/utils.ts`" or "- `src/`"
    const m = line.match(/^(\s*)-\s+`([^`]+)`/);
    if (!m) continue;
    const indent = m[1].length;
    const path = m[2];
    const isDir = path.endsWith("/");
    const cleanPath = isDir ? path.slice(0, -1) : path;
    const depth = Math.floor(indent / 2);
    entries.push({ path: cleanPath, isDir, ext: isDir ? "" : extname(path), depth });
  }
  return entries;
}

// ---------------------------------------------------------------------------
// generateCodebaseMap
// ---------------------------------------------------------------------------

/**
 * Scan the project directory and generate a CodebaseMapEntry array.
 */
export function generateCodebaseMap(
  rootDir: string,
  options: CodebaseMapOptions = {},
): CodebaseMapEntry[] {
  const {
    excludePatterns = [],
    maxFiles = 500,
    collapseThreshold = 3,
  } = options;

  const allPatterns = [...DEFAULT_EXCLUDE_PATTERNS, ...excludePatterns];
  const counter = { n: 0 };

  return scanDir(rootDir, rootDir, allPatterns, maxFiles, collapseThreshold, counter, 0);
}

// ---------------------------------------------------------------------------
// updateCodebaseMap
// ---------------------------------------------------------------------------

/**
 * Update an existing map by adding new entries and removing stale ones.
 * Returns the merged entry list.
 */
export function updateCodebaseMap(
  existing: CodebaseMapEntry[],
  fresh: CodebaseMapEntry[],
): CodebaseMapEntry[] {
  const freshPaths = new Set(fresh.map((e) => e.path));
  // Remove entries no longer present in the fresh scan
  const retained = existing.filter((e) => freshPaths.has(e.path));
  const retainedPaths = new Set(retained.map((e) => e.path));
  // Add new entries from the fresh scan
  const added = fresh.filter((e) => !retainedPaths.has(e.path));
  return [...retained, ...added];
}

// ---------------------------------------------------------------------------
// Serialization helpers
// ---------------------------------------------------------------------------

function entriesToMarkdown(entries: CodebaseMapEntry[], generatedAt: string): string {
  const lines: string[] = [CODEBASE_MAP_HEADER.trimEnd(), "", `*Generated: ${generatedAt}*`, ""];
  for (const entry of entries) {
    const indent = "  ".repeat(entry.depth);
    const label = entry.isDir ? `${entry.path}/` : entry.path;
    lines.push(`${indent}- \`${label}\``);
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// writeCodebaseMap / readCodebaseMap
// ---------------------------------------------------------------------------

/**
 * Write the codebase map to .hx/CODEBASE.md.
 */
export function writeCodebaseMap(basePath: string, entries: CodebaseMapEntry[]): void {
  const root = hxRoot(basePath);
  const outPath = join(root, "CODEBASE.md");
  const generatedAt = new Date().toISOString();
  const content = entriesToMarkdown(entries, generatedAt);
  writeFileSync(outPath, content, "utf-8");
}

/**
 * Read and parse .hx/CODEBASE.md. Returns null if absent.
 */
export function readCodebaseMap(basePath: string): CodebaseMapEntry[] | null {
  const root = hxRoot(basePath);
  const mapPath = join(root, "CODEBASE.md");
  if (!existsSync(mapPath)) return null;
  try {
    const raw = readFileSync(mapPath, "utf-8");
    return parseCodebaseMap(raw);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// getCodebaseMapStats
// ---------------------------------------------------------------------------

/**
 * Compute statistics for a set of codebase map entries.
 */
export function getCodebaseMapStats(entries: CodebaseMapEntry[]): CodebaseMapStats {
  const files = entries.filter((e) => !e.isDir);
  const dirs = entries.filter((e) => e.isDir);

  const filesByExtension: Record<string, number> = {};
  for (const f of files) {
    const ext = f.ext || "(no ext)";
    filesByExtension[ext] = (filesByExtension[ext] ?? 0) + 1;
  }

  const topLevelEntries = entries.filter((e) => e.depth === 0).length;

  return {
    totalFiles: files.length,
    totalDirs: dirs.length,
    filesByExtension,
    topLevelEntries,
    generatedAt: new Date().toISOString(),
  };
}
