/**
 * codebase-generator tests
 *
 * Tests the codebase map generation, parsing, updating, stats, and roundtrip
 * write/read functions. Uses real temp directories — no mocks.
 */

import { describe, test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';

import {
  parseCodebaseMap,
  generateCodebaseMap,
  updateCodebaseMap,
  getCodebaseMapStats,
  writeCodebaseMap,
  readCodebaseMap,
  DEFAULT_EXCLUDE_PATTERNS,
} from '../codebase-generator.js';

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

interface TmpRepo {
  dir: string;
  hxDir: string;
  write: (relPath: string, content?: string) => void;
  mkdir: (relPath: string) => void;
}

function makeTmpRepo(): TmpRepo {
  const dir = mkdtempSync(join(tmpdir(), 'hx-codebase-test-'));

  // git init so hxRoot() probe works
  spawnSync('git', ['init', '-q'], { cwd: dir });

  const hxDir = join(dir, '.hx');
  mkdirSync(hxDir, { recursive: true });

  return {
    dir,
    hxDir,
    write(relPath: string, content = `// ${relPath}`) {
      const full = join(dir, relPath);
      mkdirSync(join(full, '..'), { recursive: true });
      writeFileSync(full, content, 'utf-8');
    },
    mkdir(relPath: string) {
      mkdirSync(join(dir, relPath), { recursive: true });
    },
  };
}

function cleanupRepo(r: TmpRepo) {
  try { rmSync(r.dir, { recursive: true, force: true }); } catch { /* best-effort */ }
}

// ---------------------------------------------------------------------------
// parseCodebaseMap tests
// ---------------------------------------------------------------------------

describe('parseCodebaseMap', () => {
  test('returns empty array for empty string', () => {
    assert.deepEqual(parseCodebaseMap(''), []);
  });

  test('returns empty array for header-only content', () => {
    const raw = '# Codebase Map\n\nGenerated by HX.\n\n*Generated: 2024-01-01*\n';
    assert.deepEqual(parseCodebaseMap(raw), []);
  });

  test('parses file entries', () => {
    const raw = '# Codebase Map\n\n- `src/index.ts`\n- `src/utils.ts`\n';
    const entries = parseCodebaseMap(raw);
    assert.equal(entries.length, 2);
    assert.equal(entries[0].path, 'src/index.ts');
    assert.equal(entries[0].isDir, false);
    assert.equal(entries[0].ext, '.ts');
    assert.equal(entries[0].depth, 0);
  });

  test('parses directory entries (trailing slash)', () => {
    const raw = '- `src/`\n  - `src/index.ts`\n';
    const entries = parseCodebaseMap(raw);
    assert.equal(entries.length, 2);
    assert.equal(entries[0].path, 'src');
    assert.equal(entries[0].isDir, true);
    assert.equal(entries[1].path, 'src/index.ts');
    assert.equal(entries[1].depth, 1);
  });

  test('parses mixed depths', () => {
    const raw = '- `src/`\n  - `src/lib/`\n    - `src/lib/helpers.ts`\n';
    const entries = parseCodebaseMap(raw);
    assert.equal(entries[0].depth, 0);
    assert.equal(entries[1].depth, 1);
    assert.equal(entries[2].depth, 2);
  });
});

// ---------------------------------------------------------------------------
// generateCodebaseMap tests
// ---------------------------------------------------------------------------

describe('generateCodebaseMap', () => {
  test('generates entries for a simple project', () => {
    const r = makeTmpRepo();
    try {
      r.write('src/index.ts');
      r.write('src/utils.ts');
      r.write('README.md');

      const entries = generateCodebaseMap(r.dir, {});
      const paths = entries.map((e) => e.path);
      assert.ok(paths.includes('README.md'), 'README.md should be in entries');
      assert.ok(paths.some((p) => p.includes('index.ts')), 'index.ts should be in entries');
    } finally {
      cleanupRepo(r);
    }
  });

  test('excludes .hx/ by default', () => {
    const r = makeTmpRepo();
    try {
      r.write('src/index.ts');
      writeFileSync(join(r.hxDir, 'STATE.md'), '# State\n');

      const entries = generateCodebaseMap(r.dir, {});
      const paths = entries.map((e) => e.path);
      assert.ok(!paths.some((p) => p.startsWith('.hx')), '.hx/ should be excluded');
    } finally {
      cleanupRepo(r);
    }
  });

  test('excludes node_modules/ by default', () => {
    const r = makeTmpRepo();
    try {
      r.mkdir('node_modules/some-pkg');
      r.write('node_modules/some-pkg/index.js');
      r.write('src/index.ts');

      const entries = generateCodebaseMap(r.dir, {});
      const paths = entries.map((e) => e.path);
      assert.ok(!paths.some((p) => p.startsWith('node_modules')), 'node_modules/ should be excluded');
    } finally {
      cleanupRepo(r);
    }
  });

  test('respects custom exclude patterns', () => {
    const r = makeTmpRepo();
    try {
      r.write('src/index.ts');
      r.write('generated/output.ts');

      const entries = generateCodebaseMap(r.dir, { excludePatterns: ['generated/'] });
      const paths = entries.map((e) => e.path);
      assert.ok(!paths.some((p) => p.startsWith('generated')), 'generated/ should be excluded');
    } finally {
      cleanupRepo(r);
    }
  });

  test('respects maxFiles limit', () => {
    const r = makeTmpRepo();
    try {
      for (let i = 0; i < 20; i++) r.write(`src/file${i}.ts`);

      const entries = generateCodebaseMap(r.dir, { maxFiles: 5 });
      const fileCount = entries.filter((e) => !e.isDir).length;
      assert.ok(fileCount <= 5, `Expected ≤5 files, got ${fileCount}`);
    } finally {
      cleanupRepo(r);
    }
  });

  test('depth is correct for nested files', () => {
    const r = makeTmpRepo();
    try {
      r.write('a/b/c/deep.ts');

      const entries = generateCodebaseMap(r.dir, { collapseThreshold: 0 });
      const deepEntry = entries.find((e) => e.path.endsWith('deep.ts'));
      assert.ok(deepEntry, 'deep.ts should be present');
      assert.equal(deepEntry.depth, 3);
    } finally {
      cleanupRepo(r);
    }
  });
});

// ---------------------------------------------------------------------------
// updateCodebaseMap tests
// ---------------------------------------------------------------------------

describe('updateCodebaseMap', () => {
  test('adds new entries from fresh scan', () => {
    const existing = [
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
    ];
    const fresh = [
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
      { path: 'src/utils.ts', isDir: false, ext: '.ts', depth: 1 },
    ];

    const merged = updateCodebaseMap(existing, fresh);
    assert.equal(merged.length, 2);
    assert.ok(merged.some((e) => e.path === 'src/utils.ts'));
  });

  test('removes stale entries not in fresh scan', () => {
    const existing = [
      { path: 'src/old.ts', isDir: false, ext: '.ts', depth: 1 },
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
    ];
    const fresh = [
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
    ];

    const merged = updateCodebaseMap(existing, fresh);
    assert.equal(merged.length, 1);
    assert.equal(merged[0].path, 'src/index.ts');
    assert.ok(!merged.some((e) => e.path === 'src/old.ts'));
  });

  test('preserves all entries when fresh matches existing', () => {
    const entries = [
      { path: 'a.ts', isDir: false, ext: '.ts', depth: 0 },
      { path: 'b.ts', isDir: false, ext: '.ts', depth: 0 },
    ];
    const merged = updateCodebaseMap(entries, entries);
    assert.equal(merged.length, 2);
  });

  test('returns all fresh entries when existing is empty', () => {
    const fresh = [
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
      { path: 'src/utils.ts', isDir: false, ext: '.ts', depth: 1 },
    ];
    const merged = updateCodebaseMap([], fresh);
    assert.equal(merged.length, 2);
  });
});

// ---------------------------------------------------------------------------
// getCodebaseMapStats tests
// ---------------------------------------------------------------------------

describe('getCodebaseMapStats', () => {
  test('returns zeros for empty entries', () => {
    const stats = getCodebaseMapStats([]);
    assert.equal(stats.totalFiles, 0);
    assert.equal(stats.totalDirs, 0);
    assert.equal(stats.topLevelEntries, 0);
  });

  test('counts files and dirs correctly', () => {
    const entries = [
      { path: 'src', isDir: true, ext: '', depth: 0 },
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
      { path: 'src/utils.ts', isDir: false, ext: '.ts', depth: 1 },
      { path: 'README.md', isDir: false, ext: '.md', depth: 0 },
    ];
    const stats = getCodebaseMapStats(entries);
    assert.equal(stats.totalFiles, 3);
    assert.equal(stats.totalDirs, 1);
  });

  test('counts files by extension', () => {
    const entries = [
      { path: 'a.ts', isDir: false, ext: '.ts', depth: 0 },
      { path: 'b.ts', isDir: false, ext: '.ts', depth: 0 },
      { path: 'c.md', isDir: false, ext: '.md', depth: 0 },
    ];
    const stats = getCodebaseMapStats(entries);
    assert.equal(stats.filesByExtension['.ts'], 2);
    assert.equal(stats.filesByExtension['.md'], 1);
  });

  test('counts top-level entries', () => {
    const entries = [
      { path: 'src', isDir: true, ext: '', depth: 0 },
      { path: 'README.md', isDir: false, ext: '.md', depth: 0 },
      { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
    ];
    const stats = getCodebaseMapStats(entries);
    assert.equal(stats.topLevelEntries, 2);
  });
});

// ---------------------------------------------------------------------------
// writeCodebaseMap / readCodebaseMap roundtrip tests
// ---------------------------------------------------------------------------

describe('writeCodebaseMap / readCodebaseMap', () => {
  test('roundtrip write and read preserves file entries', () => {
    const r = makeTmpRepo();
    try {
      const entries = [
        { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
        { path: 'src/utils.ts', isDir: false, ext: '.ts', depth: 1 },
      ];

      writeCodebaseMap(r.dir, entries);

      assert.ok(existsSync(join(r.hxDir, 'CODEBASE.md')), 'CODEBASE.md should exist');

      const read = readCodebaseMap(r.dir);
      assert.ok(read !== null);
      assert.equal(read.length, 2);
      const paths = read.map((e) => e.path);
      assert.ok(paths.includes('src/index.ts'));
      assert.ok(paths.includes('src/utils.ts'));
    } finally {
      cleanupRepo(r);
    }
  });

  test('readCodebaseMap returns null when CODEBASE.md absent', () => {
    const r = makeTmpRepo();
    try {
      const result = readCodebaseMap(r.dir);
      assert.equal(result, null);
    } finally {
      cleanupRepo(r);
    }
  });

  test('roundtrip preserves directory entries', () => {
    const r = makeTmpRepo();
    try {
      const entries = [
        { path: 'src', isDir: true, ext: '', depth: 0 },
        { path: 'src/index.ts', isDir: false, ext: '.ts', depth: 1 },
      ];

      writeCodebaseMap(r.dir, entries);
      const read = readCodebaseMap(r.dir);
      assert.ok(read !== null);
      const dirEntry = read.find((e) => e.path === 'src');
      assert.ok(dirEntry, 'src directory entry should be present');
      assert.equal(dirEntry.isDir, true);
    } finally {
      cleanupRepo(r);
    }
  });

  test('write overwrites existing CODEBASE.md', () => {
    const r = makeTmpRepo();
    try {
      writeCodebaseMap(r.dir, [{ path: 'old.ts', isDir: false, ext: '.ts', depth: 0 }]);
      writeCodebaseMap(r.dir, [{ path: 'new.ts', isDir: false, ext: '.ts', depth: 0 }]);

      const read = readCodebaseMap(r.dir);
      assert.ok(read !== null);
      assert.equal(read.length, 1);
      assert.equal(read[0].path, 'new.ts');
    } finally {
      cleanupRepo(r);
    }
  });
});
